# Generated by Django 3.2.8 on 2022-11-02 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=15)),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.fooddata')),
            ],
        ),
    ]
